const jobs = {
  onCampusJobs: [
    {
      id: 1,
      title: 'Campus IT Support Specialist',
      company: 'University Tech Services',
      description: 'Assist in maintaining campus technology infrastructure, troubleshoot hardware/software issues, and support students and faculty with technical needs.',
      location: 'On-Campus, University Support Center',
      salaryRange: '$20 - $25 per hour',
    },
    {
      id: 2,
      title: 'Research Assistant',
      company: 'University Research Lab',
      description: 'Collaborate with professors and researchers on projects related to software engineering, AI, or data science. Involve in coding, data analysis, and report generation.',
      location: 'On-Campus, Research Department',
      salaryRange: '$15 - $22 per hour',
    },
  ],
  
  onCampusInternships: [
    {
      id: 3,
      title: 'Software Development Intern',
      company: 'University Innovation Hub',
      description: 'Work with the university’s innovation team to develop software solutions for campus systems, focusing on real-world applications and user experience.',
      location: 'On-Campus, Innovation Center',
      salaryRange: '$18 - $22 per hour',
    },
    {
      id: 4,
      title: 'Data Science Intern',
      company: 'Campus Data Lab',
      description: 'Analyze student data to help improve campus services, focusing on creating predictive models and visualizations.',
      location: 'On-Campus, Data Science Department',
      salaryRange: '$18 - $25 per hour',
    },
  ],

  offCampusJobs: [
    {
      id: 5,
      title: 'Software Engineer',
      company: 'Google',
      description: 'Work on scalable systems, develop new features, and optimize performance for Google’s search engine.',
      location: 'Mountain View, CA',
      salaryRange: '$120,000 - $180,000',
    },
    {
      id: 6,
      title: 'Product Manager',
      company: 'Meta (Facebook)',
      description: 'Oversee product development, strategize user engagement, and collaborate with cross-functional teams to launch new features.',
      location: 'Menlo Park, CA',
      salaryRange: '$130,000 - $200,000',
    },
    {
      id: 7,
      title: 'Data Scientist',
      company: 'Netflix',
      description: 'Analyze user data to provide insights for personalized recommendations and improve user experience.',
      location: 'Los Gatos, CA',
      salaryRange: '$140,000 - $190,000',
    },
    {
      id: 8,
      title: 'Cloud Solutions Architect',
      company: 'Amazon Web Services (AWS)',
      description: 'Design and deploy scalable cloud solutions, optimize architecture, and collaborate with clients on cloud strategies.',
      location: 'Seattle, WA',
      salaryRange: '$150,000 - $210,000',
    },
    {
      id: 9,
      title: 'UX Designer',
      company: 'Apple',
      description: 'Design intuitive interfaces and experiences for Apple’s suite of software and hardware products, focusing on user-centric design.',
      location: 'Cupertino, CA',
      salaryRange: '$110,000 - $160,000',
    },
    {
      id: 10,
      title: 'Machine Learning Engineer',
      company: 'Microsoft',
      description: 'Develop machine learning models and algorithms to enhance products such as Azure, Office, and Windows.',
      location: 'Redmond, WA',
      salaryRange: '$125,000 - $190,000',
    },
    {
      id: 11,
      title: 'Backend Engineer',
      company: 'Amazon',
      description: 'Build and maintain server-side applications, APIs, and microservices to support e-commerce and cloud infrastructure.',
      location: 'Seattle, WA',
      salaryRange: '$115,000 - $175,000',
    },
    {
      id: 12,
      title: 'DevOps Engineer',
      company: 'IBM',
      description: 'Implement CI/CD pipelines, automate infrastructure deployment, and ensure efficient system operations.',
      location: 'Armonk, NY',
      salaryRange: '$105,000 - $160,000',
    },
    {
      id: 13,
      title: 'Security Engineer',
      company: 'Netflix',
      description: 'Design and implement security protocols, conduct threat analysis, and safeguard Netflix’s streaming services from attacks.',
      location: 'Los Gatos, CA',
      salaryRange: '$130,000 - $180,000',
    },
    {
      id: 14,
      title: 'Front-End Developer',
      company: 'Meta (Instagram)',
      description: 'Create dynamic and responsive user interfaces for Instagram’s web and mobile applications.',
      location: 'San Francisco, CA',
      salaryRange: '$115,000 - $165,000',
    },
  ],
};

export default jobs;
